### ISSUE TITLE
Only showing black even after refreshing extension

### ISSUE THREAD

**Issue by matthewgallo** [IBM-Design/spongy#23]
Eye dropper only showing black when clicking on colors, even after pressing "R" to refresh the extension.

![spongy_bug](https://cloud.githubusercontent.com/assets/10215203/21938091/74607a2e-d97f-11e6-83ab-c59156448942.gif)

**Comment by diego-codes** [comment]
@matthewgallo I just pushed some changes to master that may have solved this problem. Let me know if you're still having the same problem once you reinstall the extension! Thanks.

**Comment by diego-codes** [comment]
Closing this issue for now, but let me know if it comes up again.
