### ISSUE TITLE
Unable to Download spongy.crx

### ISSUE THREAD

**Issue by Candidculture** [IBM-Design/spongy#24]
Tried to save file to add to my extensions, but failed after a few loading loops. 
<img width="212" alt="screen shot 2017-01-13 at 11 00 16 am" src="https://cloud.githubusercontent.com/assets/25105397/21938133/a1ef40ec-d97f-11e6-8b59-9986e3275d92.png">

**Comment by diego-codes** [comment]
@Candidculture did it fail right away? Or did it download for a bit and then fail? Also, did you download from the link on the README or directly from the [code](https://github.com/IBM-Design/spongy/blob/master/spongy.crx)?

**Comment by Candidculture** [comment]
README. It did download for a while prior to failing. should i download from code?

**Comment by diego-codes** [comment]
This might have been a GH server issue, but @Candidculture just pushed some changes to the master branch that may have solved this problem. Let me know if you run into this issue again when you try to download the file again from the README.

**Comment by diego-codes** [comment]
Closing this issue for now, but let me know if it comes up again.
